[package]
name = "ark-host-hash-to-curve"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ark-std.workspace = true
ark-ff.workspace = true
ark-ec.workspace = true
ark-serialize = { workspace = true, features = ["derive"] }
ark-host-msm = { workspace = true, default-features = false }
sha2.workspace = true
rayon = { workspace = true, optional = true }

# Supported Curves
ark-pallas = { workspace = true, default-features = false, features = ["curve"] }
ark-vesta = { workspace = true, default-features = false }
ark-helios = { workspace = true, default-features = false }
ark-selene = { workspace = true, default-features = false }
ark-wei25519 = { workspace = true, default-features = false }

polkavm-derive = { version = "0.32.0", optional = true }

[dev-dependencies]
hex.workspace = true

[features]
default = ["std"]
std = [
    "ark-std/std",
    "ark-ff/std",
    "ark-ec/std",
    "ark-serialize/std",
    "ark-host-msm/std",
    "sha2/std",
    "ark-pallas/std",
    "ark-vesta/std",
    "ark-helios/std",
    "ark-selene/std",
    "ark-wei25519/std",
]
parallel = ["std", "rayon", "ark-std/parallel", "ark-ec/parallel"]
asm = ["ark-ff/asm"]

# Call the host function from a no_std guest.
host_hash_to_curve = []
polkavm = [
    "host_hash_to_curve",
    "polkavm-derive",
]
