[package]
name = "ark-host-msm-impl"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
include.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
ark-std.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true
ark-host-msm = { workspace = true, default-features = false }

# Supported Curves
ark-pallas = { workspace = true, default-features = false, features = ["curve"] }
ark-vesta = { workspace = true, default-features = false }

lazy_static = { version = "1.5.0", default-features = false, optional = true }

[features]
default = ["std"]
std = ["ark-std/std", "ark-ec/std", "ark-serialize/std", "lazy_static"]
parallel = ["std", "ark-std/parallel", "ark-ec/parallel", "ark-serialize/parallel"]
asm = ["ark-ff/asm"]
